# Generated by Django 5.2.8 on 2026-01-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0004_event_external_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='citizenship',
            field=models.CharField(default='', max_length=100, verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='full_name',
            field=models.CharField(default='', max_length=255, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='job_title',
            field=models.CharField(default='', max_length=150, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='place_of_work',
            field=models.CharField(default='', max_length=255, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='additional_info',
            field=models.TextField(blank=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено'),
        ),
    ]
