# Generated by Django 5.2.8 on 2026-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0005_membershipapplication_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_international',
            field=models.BooleanField(default=False, verbose_name='Зарубежное мероприятие'),
        ),
    ]
