# Generated by Django 5.2.8 on 2026-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0006_event_is_international'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст даты (вручную)'),
        ),
    ]
