# Generated by Django 5.2.8 on 2026-03-04 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0007_event_date_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='citizenship',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='agreement_accepted',
            field=models.BooleanField(default=False, verbose_name='Подтверждение'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='id_card_copy',
            field=models.FileField(blank=True, null=True, upload_to='applications/id_cards/', verbose_name='Копия удостоверения личности'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='applications/receipts/', verbose_name='Чек об оплате'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сведения о квалификации / категория'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место жительства'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заполнения'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='degree',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Наличие ученой степени или звания'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='Занимаемая должность'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
