# Generated by Django 5.2.8 on 2026-03-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0008_remove_membershipapplication_additional_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipapplication',
            name='residence',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Город'),
        ),
    ]
