# Generated by Django 5.2.8 on 2026-03-17 20:00

from django.db import migrations
from django.utils import timezone
import datetime

def fix_data(apps, schema_editor):
    News = apps.get_model('webkato', 'News')
    NewsCategory = apps.get_model('webkato', 'NewsCategory')
    Event = apps.get_model('webkato', 'Event')

    # Update News dates
    news_updates = [
        ('cadaver-courses-karaganda-v3', datetime.datetime(2025, 9, 5)),
        ('ao-trauma-seminar-v3', datetime.datetime(2025, 9, 5)),
        ('astana-congress-rook-v3', datetime.datetime(2024, 8, 8)),
        ('iv-congress-postponed-v3', datetime.datetime(2024, 4, 23)),
        ('kato-china-memorandum-v3', datetime.datetime(2024, 3, 20)),
        ('medical-companies-invitation-v3', datetime.datetime(2024, 3, 20)),
        ('benoit-dolle-nncto-v3', datetime.datetime(2024, 1, 1)),
    ]

    for slug, date in news_updates:
        News.objects.filter(slug=slug).update(created_at=timezone.make_aware(date))

    # Fix Karaganda 2025 Event
    Event.objects.filter(slug='karaganda-2025-v3').update(
        image='events/karaganda_poster.png',
        external_link='https://conference.nscto.online/',
        is_active=False # Should be in archive
    )

def remove_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0010_add_initial_data_v3'),
    ]

    operations = [
        migrations.RunPython(fix_data, remove_data),
    ]
