# Generated by Django 5.2.8 on 2026-03-17 22:09

from django.db import migrations

def update_image(apps, schema_editor):
    Event = apps.get_model('webkato', 'Event')
    Event.objects.filter(slug='karaganda-2025-v3').update(
        image='events/2025.png'
    )

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0011_fix_data_v4'),
    ]

    operations = [
        migrations.RunPython(update_image, reverse_update),
    ]
