from django.db import migrations
from django.utils import timezone
import datetime

def add_intl_events(apps, schema_editor):
    Event = apps.get_model('webkato', 'Event')
    
    events_data = [
        {
            'title': "Всероссийская конференция молодых ученых «Вреденовские игры»",
            'slug': "vserossiyskaya-konferentsiya-molodyh-uchenyh-vredenovskie-igry",
            'date': "2026-04-10",
            'date_text': "10 апреля 2026",
            'location': "Санкт-Петербург, НМИЦ ТО им. Вредена",
            'description': "Формат: очно (300 участников)<br>Контакты: +7 (965) 073-38-81 med-03@yandex.ru",
            'external_link': "https://rniito.ru/",
            'is_international': True,
        },
        {
            'title': "V Съезд травматологов-ортопедов УФО «Мультидисциплинарный подход…»",
            'slug': "v-sezd-travmatologov-ortopedov-ufo-multidistsiplinarnyy-podhod",
            'date': "2026-04-17",
            'date_text': "17 апреля 2026",
            'location': "Екатеринбург",
            'description': "Формат: очно (300 участников)<br>Контакты: 8 (3522) 45-47-47 office@ilizarov.ru",
            'external_link': "https://meeting.ilizarov.ru/",
            'is_international': True,
        },
        {
            'title': "Всероссийская конференция «Реабилитация и консервативное лечение…»",
            'slug': "vserossiyskaya-konferentsiya-reabilitatsiya-i-konservativnoe-lechenie",
            'date': "2026-04-24",
            'date_text': "24 апреля 2026",
            'location': "Санкт-Петербург",
            'description': "Формат: очно (500 участников)<br>Контакты: +7 (911) 223-20-66",
            'external_link': "https://rniito.ru/",
            'is_international': True,
        },
        {
            'title': "VII Конгресс «ОРТОБИОЛОГИЯ 2026» «Будущее начинается здесь»",
            'slug': "vii-kongress-ortobiologiya-2026-buduschee-nachinaetsya-zdes",
            'date': "2026-04-24",
            'date_text': "24–25 апреля 2026",
            'location': "Москва, Holiday Inn Сокольники",
            'description': "Формат: очно (600 участников)<br>Контакты: +7 981 126-65-87 alena.trofimova@congress-ph.ru",
            'external_link': "http://orthobio.ru",
            'is_international': True,
        },
        {
            'title': "Конференция «Ярославская весна. Только косолапость»",
            'slug': "konferentsiya-yaroslavskaya-vesna-tolko-kosolapost",
            'date': "2026-05-01",
            'date_text': "1 мая 2026",
            'location': "Ярославль",
            'description': "Формат: очно (180 участников)<br>Контакты: +7 903 823-38-66",
            'external_link': "https://www.ysmu.ru",
            'is_international': True,
        },
        {
            'title': "Российский ортопедический конгресс «Наука, инновации и практика»",
            'slug': "rossiyskiy-ortopedicheskiy-kongress-nauka-innovatsii-i-praktika",
            'date': "2026-05-14",
            'date_text': "14–15 мая 2026",
            'location': "Уфа",
            'description': "Формат: очно (400 участников)<br>Контакты: b.minasov@yandex.ru",
            'external_link': "",
            'is_international': True,
        },
        {
            'title': "Международная научно-образовательная конференция «Теория и практика современной травматологии…»",
            'slug': "mezhdunarodnaya-nauchno-obrazovatelnaya-konferentsiya-teoriya-i-praktika-sovremennoy-travmatologii",
            'date': "2026-05-21",
            'date_text': "21 мая 2026",
            'location': "Москва",
            'description': "Формат: очно (300 участников)<br>Контакты: +7 903 207-30-95",
            'external_link': "https://pirogovforum.com/",
            'is_international': True,
        },
        {
            'title': "VIII Съезд травматологов СФО",
            'slug': "viii-sezd-travmatologov-sfo",
            'date': "2026-05-21",
            'date_text': "21–22 мая 2026",
            'location': "Барнаул",
            'description': "Формат: очно (400 участников)",
            'external_link': "https://www.orthobarnaul.ru/",
            'is_international': True,
        },
        {
            'title': "XIII Всероссийский конгресс кистевых хирургов",
            'slug': "xiii-vserossiyskiy-kongress-kistevyh-hirurgov",
            'date': "2026-05-21",
            'date_text': "21–23 мая 2026",
            'location': "Махачкала",
            'description': "Формат: очно (300 участников)<br>Контакты: +7 (999) 121-39-43",
            'external_link': "https://nn-terra.ru",
            'is_international': True,
        },
        {
            'title': "Межрегиональная конференция «Гражданская и военная травматология…»",
            'slug': "mezhregionalnaya-konferentsiya-grazhdanskaya-i-voennaya-travmatologiya",
            'date': "2026-05-22",
            'date_text': "22 мая 2026",
            'location': "Воронеж",
            'description': "Формат: очно (160 участников)<br>Контакты: +7 919 187-89-50",
            'external_link': "",
            'is_international': True,
        },
        {
            'title': "Конференция памяти проф. Ключевского",
            'slug': "konferentsiya-pamyati-prof-klyuchevskogo",
            'date': "2026-05-22",
            'date_text': "22 мая 2026",
            'location': "Ярославль",
            'description': "Формат: очно (180 участников)",
            'external_link': "https://www.ysmu.ru",
            'is_international': True,
        },
        {
            'title': "VII Межрегиональный Травмафорум",
            'slug': "vii-mezhregionalnyy-travmaforum",
            'date': "2026-05-22",
            'date_text': "22–23 мая 2026",
            'location': "Челябинск",
            'description': "Формат: очно (300 участников)",
            'external_link': "https://travmaforum.ru/",
            'is_international': True,
        },
        {
            'title': "FAILMEDCON 2026",
            'slug': "failmedcon-2026",
            'date': "2026-05-29",
            'date_text': "29 мая 2026",
            'location': "Москва",
            'description': "Формат: очно (300 участников)<br>Контакты: +7 925 064-33-50",
            'external_link': "https://failmedcon.ru/",
            'is_international': True,
        },
        {
            'title': "Московский ортопедический форум",
            'slug': "moskovskiy-ortopedicheskiy-forum",
            'date': "2026-06-05",
            'date_text': "5–6 июня 2026",
            'location': "Москва, кластер «Ломоносов»",
            'description': "Формат: очно (1000 участников)<br>Контакты: airapetovga@yandex.ru",
            'external_link': "",
            'is_international': True,
        },
        {
            'title': "XII Всероссийская Олимпиада ординаторов (Травматология и ортопедия)",
            'slug': "xii-vserossiyskaya-olimpiada-ordinatorov-travmatologiya-i-ortopediya",
            'date': "2026-06-05",
            'date_text': "5–6 июня 2026",
            'location': "Смоленск",
            'description': "Формат: очно (150 участников)<br>Контакты: +7 (908) 284-25-61 Marina.Vlasova@orthosmolensk.ru",
            'external_link': "https://orthosmolensk.ru/",
            'is_international': True,
        },
        {
            'title': "Конференция «Травматология и ортопедия Дальнего Востока…»",
            'slug': "konferentsiya-travmatologiya-i-ortopediya-dalnego-vostoka",
            'date': "2026-06-10",
            'date_text': "10–11 июня 2026",
            'location': "Хабаровск",
            'description': "Формат: смешанный (200 очно / 500 онлайн)<br>Контакты: +7 914 165-89-63 volovik2013@mail.ru",
            'external_link': "http://www.medum.org",
            'is_international': True,
        },
        {
            'title': "«Илизаровские чтения – 2026»",
            'slug': "ilizarovskie-chteniya-2026",
            'date': "2026-06-15",
            'date_text': "15–16 июня 2026",
            'location': "Курган",
            'description': "Формат: смешанный (300 очно / 700 онлайн)<br>Контакты: 8 (3522) 45-47-47 office@ilizarov.ru",
            'external_link': "https://meeting.ilizarov.ru/",
            'is_international': True,
        },
        {
            'title': "Международная школа АРТРОМАСТЕР 2026",
            'slug': "mezhdunarodnaya-shkola-artromaster-2026",
            'date': "2026-06-19",
            'date_text': "19–21 июня 2026",
            'location': "Казань",
            'description': "Формат: очно (500 участников)<br>Контакты: +7 927 891-93-93",
            'external_link': "https://amtec-kazan.com",
            'is_international': True,
        },
        {
            'title': "Конференция «Актуальные вопросы эндопротезирования крупных суставов»",
            'slug': "konferentsiya-aktualnye-voprosy-endoprotezirovaniya-krupnyh-sustavov",
            'date': "2026-06-26",
            'date_text': "26 июня 2026",
            'location': "Чебоксары",
            'description': "Формат: смешанный (150 очно / 500 онлайн)<br>Контакты: 8 (8352) 70-60-03 aranovich@orthoscheb.ru",
            'external_link': "https://orthoscheb.ru/",
            'is_international': True,
        },
        {
            'title': "Международный конгресс Российского артроскопического общества",
            'slug': "mezhdunarodnyy-kongress-rossiyskogo-artroskopicheskogo-obschestva",
            'date': "2026-08-29",
            'date_text': "29 августа 2026",
            'location': "Москва",
            'description': "Формат: очно (300 участников)<br>Контакты: russian-arthroscopy@mail.ru",
            'external_link': "",
            'is_international': True,
        },
        {
            'title': "«Вреденовские чтения»",
            'slug': "vredenovskie-chteniya",
            'date': "2026-09-03",
            'date_text': "3–4 сентября 2026",
            'location': "Санкт-Петербург, Экспофорум",
            'description': "Формат: очно (5000 участников)<br>Контакты: +7 (812) 670-89-05",
            'external_link': "https://rniito.ru/",
            'is_international': True,
        },
        {
            'title': "X Международный конгресс ревмоортопедов",
            'slug': "x-mezhdunarodnyy-kongress-revmoortopedov",
            'date': "2026-09-11",
            'date_text': "11–12 сентября 2026",
            'location': "Москва",
            'description': "Формат: очно (700 участников)<br>Контакты: +7 925 064-33-50",
            'external_link': "https://2026.rheumo.surgery/",
            'is_international': True,
        },
        {
            'title': "«Турнеровские чтения»",
            'slug': "turnerovskie-chteniya",
            'date': "2026-10-08",
            'date_text': "8–9 октября 2026",
            'location': "Санкт-Петербург",
            'description': "Формат: очно (350 участников)<br>Контакты: 8 (812) 465-56-84 omoturner@mail.ru",
            'external_link': "http://www.turnerreadings.org",
            'is_international': True,
        },
        {
            'title': "Чаклинские чтения – 2026",
            'slug': "chaklinskie-chteniya-2026",
            'date': "2026-10-08",
            'date_text': "8–9 октября 2026",
            'location': "Екатеринбург",
            'description': "Формат: очно (300 участников)<br>Контакты: +7 902 260-26-03",
            'external_link': "http://www.med-expo.org",
            'is_international': True,
        },
        {
            'title': "Конференция «Актуальные вопросы травматологии мирного и военного времени»",
            'slug': "konferentsiya-aktualnye-voprosy-travmatologii-mirnogo-i-voennogo-vremeni",
            'date': "2026-10-22",
            'date_text': "22–23 октября 2026",
            'location': "Донецк",
            'description': "Формат: смешанный (300 участников)<br>Контакты: +7 949 313-08-00",
            'external_link': "https://rtc-dnr.gosuslugi.ru/",
            'is_international': True,
        },
        {
            'title': "Конференция «Проблемы и инновации в травматологии…»",
            'slug': "konferentsiya-problemy-i-innovatsii-v-travmatologii",
            'date': "2026-10-23",
            'date_text': "23 октября 2026",
            'location': "Воронеж",
            'description': "Формат: очно (160 участников)<br>Контакты: +7 919 187-89-50",
            'external_link': "",
            'is_international': True,
        },
        {
            'title': "Сибирский ортопедический форум (Цивьяновские чтения)",
            'slug': "sibirskiy-ortopedicheskiy-forum-tsivyanovskie-chteniya",
            'date': "2026-10-30",
            'date_text': "30–31 октября 2026",
            'location': "Новосибирск",
            'description': "Формат: очно (500 участников)<br>Контакты: +7 (383) 373-32-01",
            'external_link': "",
            'is_international': True,
        },
        {
            'title': "Международный Пироговский forum травматологов-ортопедов",
            'slug': "mezhdunarodnyy-pirogovskiy-forum-travmatologov-ortopedov",
            'date': "2026-11-16",
            'date_text': "16–17 ноября 2026",
            'location': "Москва",
            'description': "Формат: очно (600 участников)<br>Контакты: +7 903 207-30-95",
            'external_link': "https://pirogovforum.com/",
            'is_international': True,
        },
        {
            'title': "XIII Всероссийский съезд травматологов-ортопедов",
            'slug': "xiii-vserossiyskiy-sezd-travmatologov-ortopedov",
            'date': "2026-12-09",
            'date_text': "9–11 декабря 2026",
            'location': "Казань",
            'description': "Формат: очно (3000 участников)<br>Контакты: cito-omo@mail.ru",
            'external_link': "",
            'is_international': True,
        },
    ]
    
    for item in events_data:
        # Convert date string to actual date object
        dt = datetime.datetime.strptime(item['date'], "%Y-%m-%d")
        aware_dt = timezone.make_aware(dt)
        
        Event.objects.update_or_create(
            slug=item['slug'],
            defaults={
                'title': item['title'],
                'date': aware_dt,
                'date_text': item['date_text'],
                'location': item['location'],
                'description': item['description'],
                'external_link': item['external_link'],
                'is_international': item['is_international'],
                'is_active': True
            }
        )

def remove_intl_events(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0012_update_karaganda_image_v5'),
    ]

    operations = [
        migrations.RunPython(add_intl_events, remove_intl_events),
    ]
