# Generated by Django 5.2.8 on 2026-03-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webkato', '0013_add_intl_events_2026_v6'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='specialty',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Специальность'),
        ),
    ]
